.PHONY: up sef test test-browser install clean

# Port for the local dev server (override: make up PORT=9000)
PORT ?= 8000

# Bring up the editor locally: build the SEF, then serve on http://localhost:$(PORT)
up: sef
	@echo "Serving http://localhost:$(PORT)/index.html — Ctrl-C to stop"
	python3 -m http.server $(PORT)

# Compile src/*.xsl to the SaxonJS SEF (dist/index.xsl.sef.json) and copy vocabs
sef:
	bash generate-sef.sh

# Headless XSLT test suites (extractor, canonical, lint) — run against src/ directly
test:
	bash tests/run-tests.sh

# Browser test suites (Playwright); rebuild the SEF first, as CI does
test-browser: sef
	npm run test:browser

# Install Node dependencies (Playwright) for the browser tests
install:
	npm install

# Remove generated build artifacts (dist/ is regenerated by `make sef`)
clean:
	rm -rf build dist
