<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
xmlns="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:ixsl="http://saxonica.com/ns/interactiveXSLT"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:local="urn:rdfa-editor:functions"
extension-element-prefixes="ixsl"
xpath-default-namespace="http://www.w3.org/1999/xhtml"
version="3.0">

<!--
    RDFa editor entry point. The editor UI is fully generated by this stylesheet:
    drop it onto any host page and annotate contenteditable content via right-click.

    Modules:
    - RDFa2RDFXML-v3.xsl  RDFa 1.1 to RDF/XML extraction (pure XSLT, tested headless)
    - vocab.xsl           generic ontology RDF/XML to dropdown options
    - overlay.xsl         annotation form: rendering, reading, populating, visibility
    - annotate.xsl        event handlers: right-click dispatch, apply/remove, extraction
-->

    <xsl:include href="RDFa2RDFXML-v3.xsl"/>
    <xsl:include href="vocab.xsl"/>
    <xsl:include href="overlay.xsl"/>
    <xsl:include href="annotate.xsl"/>

    <!-- ontology documents (RDF/XML) feeding the type and property dropdowns.
         Relative hrefs resolve against the SEF location (dist/) -->
    <xsl:param name="vocab-hrefs" as="xs:string*" select="('vocabs/foaf.rdf', 'vocabs/dcterms.rdf')"/>

    <!-- the page URI without its fragment: the base for RDFa resolution in the browser -->
    <xsl:function name="local:document-uri" as="xs:string">
        <xsl:sequence select="substring-before(ixsl:get(ixsl:window(), 'location.href') || '#', '#')"/>
    </xsl:function>

    <xsl:template name="main">
        <ixsl:set-property name="editingSpan" select="()" object="ixsl:window()"/>
        <!-- prefetch the vocabularies asynchronously, then render the (hidden) overlay -->
        <ixsl:schedule-action document="{string-join($vocab-hrefs, ' ')}">
            <xsl:call-template name="local:init-overlay"/>
        </ixsl:schedule-action>
    </xsl:template>

</xsl:stylesheet>
