<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
xmlns="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:ixsl="http://saxonica.com/ns/interactiveXSLT"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:local="urn:rdfa-editor:functions"
extension-element-prefixes="ixsl"
xpath-default-namespace="http://www.w3.org/1999/xhtml"
version="3.0">

<!--
    RDFa editor entry point. The editor UI is fully generated by this stylesheet:
    drop it onto any host page with a #content container and author XHTML+RDFa -
    structured block editing plus right-click RDFa annotation.

    Modules:
    - RDFa2RDFXML-v3.xsl   RDFa 1.1 to RDF/XML extraction (pure XSLT, tested headless)
    - canonical-xhtml.xsl  canonical serialization form (pure XSLT, tested headless)
    - vocab.xsl            generic ontology RDF/XML to dropdown options
    - overlay.xsl          annotation form: rendering, reading, populating, visibility
    - annotate.xsl         right-click dispatch, apply/remove annotation, extraction modal
    - edit.xsl             XHTML editing: blocks, keyboard, toolbar, dialogs, drag-and-drop
-->

    <xsl:include href="RDFa2RDFXML-v3.xsl"/>
    <xsl:include href="canonical-xhtml.xsl"/>
    <xsl:include href="lint-rdfa.xsl"/>
    <xsl:include href="vocab.xsl"/>
    <xsl:include href="overlay.xsl"/>
    <xsl:include href="annotate.xsl"/>
    <xsl:include href="edit.xsl"/>
    <xsl:include href="undo.xsl"/>
    <xsl:include href="navigate.xsl"/>

    <!-- ontology documents (RDF/XML) feeding the type and property dropdowns.
         Relative hrefs resolve against the page URI; the host page preloads them
         into the SaxonJS document pool (must match its list) -->
    <xsl:param name="vocab-hrefs" as="xs:string*" select="('vocabs/foaf.rdf', 'vocabs/dcterms.rdf')"/>

    <!-- the page URI without its fragment: the base for RDFa resolution in the browser -->
    <xsl:function name="local:document-uri" as="xs:string">
        <xsl:sequence select="substring-before(ixsl:get(ixsl:window(), 'location.href') || '#', '#')"/>
    </xsl:function>

    <xsl:template name="main">
        <xsl:for-each select="('editingSpan', 'range', 'activeBlock', 'draggedBlock',
                'editRange', 'editingLink', 'insertAfterBlock', 'lastUndoHost',
                'breadcrumbLeaf', 'draggedSectionHeading', 'findNode')">
            <ixsl:set-property name="{.}" select="()" object="ixsl:window()"/>
        </xsl:for-each>
        <ixsl:set-property name="lastUndoTime" select="0" object="ixsl:window()"/>
        <ixsl:set-property name="findOffset" select="1" object="ixsl:window()"/>
        <xsl:call-template name="local:init"/>
    </xsl:template>

    <!-- the host page preloads the vocabulary documents into the SaxonJS document
         pool (SaxonJS.getResource + documentPool), keyed by page-relative URI -->
    <xsl:template name="local:init">
        <xsl:variable name="vocab-docs" as="document-node()*"
            select="$vocab-hrefs ! doc(resolve-uri(., ixsl:location()))"/>
        <xsl:call-template name="local:init-undo"/>
        <xsl:call-template name="local:init-overlay">
            <xsl:with-param name="vocab-docs" select="$vocab-docs"/>
        </xsl:call-template>
        <xsl:call-template name="local:init-editing"/>
        <xsl:call-template name="local:init-navigate"/>
    </xsl:template>

</xsl:stylesheet>
