<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
xmlns="http://www.w3.org/1999/xhtml"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:ixsl="http://saxonica.com/ns/interactiveXSLT"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:local="urn:rdfa-editor:functions"
extension-element-prefixes="ixsl"
xpath-default-namespace="http://www.w3.org/1999/xhtml"
version="3.0">

<!--
    RDFa editor entry point. The editor UI is fully generated by this stylesheet:
    drop it onto any host page with a #content container and author XHTML+RDFa -
    structured block editing plus right-click RDFa annotation.

    Modules:
    - RDFa2RDFXML-v3.xsl   RDFa 1.1 to RDF/XML extraction (pure XSLT, tested headless)
    - canonical-xhtml.xsl  canonical serialization form (pure XSLT, tested headless)
    - vocab.xsl            generic ontology RDF/XML to dropdown options
    - overlay.xsl          annotation form: rendering, reading, populating, visibility
    - annotate.xsl         right-click dispatch, apply/remove annotation, extraction modal
    - edit.xsl             XHTML editing: blocks, keyboard, toolbar, dialogs, drag-and-drop
    - tables.xsl           table blocks: insert dialog, row/column operations, cell traversal
-->

    <xsl:include href="RDFa2RDFXML-v3.xsl"/>
    <xsl:include href="group-sort-triples.xsl"/>
    <xsl:include href="canonical-xhtml.xsl"/>
    <xsl:include href="lint-rdfa.xsl"/>
    <xsl:include href="vocab.xsl"/>
    <xsl:include href="overlay.xsl"/>
    <xsl:include href="annotate.xsl"/>
    <xsl:include href="edit.xsl"/>
    <xsl:include href="tables.xsl"/>
    <xsl:include href="undo.xsl"/>
    <xsl:include href="navigate.xsl"/>

    <!-- the initial template (SaxonJS.transform initialTemplate in the host page).
         Everything here is synchronous: the host page preloads the vocabulary
         documents into the SaxonJS document pool (SaxonJS.getResource +
         documentPool), keyed by page-relative URI -->
    <xsl:template name="main">
        <xsl:for-each select="('editingSpan', 'range', 'activeBlock', 'draggedBlock',
                'editRange', 'editingLink', 'insertAfterBlock', 'lastUndoHost',
                'breadcrumbLeaf', 'draggedSectionHeading', 'findNode')">
            <ixsl:set-property name="{.}" select="()" object="ixsl:window()"/>
        </xsl:for-each>
        <ixsl:set-property name="rdfaEditorLastUndoTime" select="0" object="ixsl:window()"/>
        <ixsl:set-property name="rdfaEditorFindOffset" select="1" object="ixsl:window()"/>

        <xsl:call-template name="local:init-undo"/>
        <xsl:call-template name="local:init-overlay"/>
        <xsl:call-template name="local:init-annotate"/>
        <xsl:call-template name="local:init-editing"/>
        <xsl:call-template name="local:init-navigate"/>
    </xsl:template>

</xsl:stylesheet>
